// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/20/2024, 9:38:30 PM
const configMerger = require("D:/webProjects/side-projects/mr_matrix/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/webProjects/side-projects/mr_matrix/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/webProjects/side-projects/mr_matrix/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/webProjects/side-projects/mr_matrix/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/webProjects/side-projects/mr_matrix/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/webProjects/side-projects/mr_matrix/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/webProjects/side-projects/mr_matrix/plugins/**/*.{js,ts,mjs}","D:/webProjects/side-projects/mr_matrix/composables/**/*.{js,ts,mjs}","D:/webProjects/side-projects/mr_matrix/utils/**/*.{js,ts,mjs}","D:/webProjects/side-projects/mr_matrix/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/webProjects/side-projects/mr_matrix/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/webProjects/side-projects/mr_matrix/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["11"] = "D:/webProjects/side-projects/mr_matrix/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
